/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/log/file_task_handler.py:187 ResourceWarning: unclosed file <_io.TextIOWrapper name='/opt/airflow/logs/dag_id=spark_tracing_example/run_id=manual__2024-12-08T17:54:58.284561+00:00/task_id=spark_task/attempt=1.log' mode='a' encoding='utf-8'>
[2024-12-08T17:55:16.174+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_tracing_example.spark_task manual__2024-12-08T17:54:58.284561+00:00 [queued]>
[2024-12-08T17:55:16.184+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_tracing_example.spark_task manual__2024-12-08T17:54:58.284561+00:00 [queued]>
[2024-12-08T17:55:16.185+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-12-08T17:55:16.202+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_task> on 2024-12-08 17:54:58.284561+00:00
[2024-12-08T17:55:16.205+0000] {standard_task_runner.py:57} INFO - Started process 76 to run task
[2024-12-08T17:55:16.210+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'spark_tracing_example', 'spark_task', 'manual__2024-12-08T17:54:58.284561+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/tracing_dag.py', '--cfg-path', '/tmp/tmpjeehs_ol']
[2024-12-08T17:55:16.212+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask spark_task
[2024-12-08T17:55:16.265+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_tracing_example.spark_task manual__2024-12-08T17:54:58.284561+00:00 [running]> on host 8994f03672a1
[2024-12-08T17:55:16.474+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_tracing_example' AIRFLOW_CTX_TASK_ID='spark_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-08T17:54:58.284561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-08T17:54:58.284561+00:00'
[2024-12-08T17:55:16.480+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-12-08T17:55:16.481+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=local[*] --conf spark.submit.deployMode=client --name arrow-spark --queue root.default /opt/airflow/spark_job.py
[2024-12-08T17:55:19.120+0000] {spark_submit.py:490} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-12-08T17:55:19.121+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-12-08T17:55:19.121+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-12-08T17:55:19.121+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-12-08T17:55:19.122+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-12-08T17:55:19.122+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1094)
[2024-12-08T17:55:19.122+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1094)
[2024-12-08T17:55:19.123+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-12-08T17:55:19.123+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
[2024-12-08T17:55:19.124+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
[2024-12-08T17:55:19.124+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-12-08T17:55:19.141+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.submit.deployMode=client --name arrow-spark --queue root.default /opt/airflow/spark_job.py. Error code is: 1.
[2024-12-08T17:55:19.146+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=spark_tracing_example, task_id=spark_task, execution_date=20241208T175458, start_date=20241208T175516, end_date=20241208T175519
[2024-12-08T17:55:19.159+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 4 for task spark_task (Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.submit.deployMode=client --name arrow-spark --queue root.default /opt/airflow/spark_job.py. Error code is: 1.; 76)
[2024-12-08T17:55:19.180+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-08T17:55:19.198+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
